function dM = get_dM(q2,q3,dq2,dq3)
%get_dM
%    dM = get_dM(Q2,Q3,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Aug-2023 18:47:48

t2 = sin(q3);
t3 = q2.*2.0;
t4 = q3.*2.0;
t5 = q3+t3;
t7 = t3+t4;
t8 = (dq3.*t2)./2.0;
t6 = sin(t5);
t9 = sin(t7);
t10 = -t8;
dM = reshape([t10-dq2.*t6-(dq3.*t6)./2.0-dq2.*t9.*(6.1e+1./2.4e+2)-dq3.*t9.*(6.1e+1./2.4e+2)-dq2.*sin(t3).*(2.47e+2./1.2e+2),0.0,0.0,0.0,-dq3.*t2,t10,0.0,t10,0.0],[3,3]);
