function [M,C,G] = get_dyn_terms(q2,q3,dq1,dq2,dq3)
%GET_DYN_TERMS
%    [M,C,G] = GET_DYN_TERMS(Q2,Q3,DQ1,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Aug-2023 00:51:59

t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t6 = q2+q3;
t7 = q2.*2.0;
t8 = cos(t6);
t9 = sin(t6);
t10 = q2+t6;
t12 = t3./2.0;
t13 = t5./4.0;
t14 = (dq2.*t5)./2.0;
t15 = (dq3.*t5)./2.0;
t19 = t2.*t4.*(2.47e+2./1.2e+2);
t11 = sin(t10);
t16 = -t15;
t20 = t8.*(9.81e+2./1.0e+2);
t21 = t12+6.7e+1./2.4e+2;
M = reshape([t12+cos(t10)./2.0+t2.^2.*(2.47e+2./1.2e+2)+t8.^2.*(6.1e+1./2.4e+2)+3.0./8.0,0.0,0.0,0.0,t3+1.91e+2./8.0e+1,t21,0.0,t21,6.7e+1./2.4e+2],[3,3]);
if nargout > 1
    t22 = t8.*t9.*(6.1e+1./2.4e+2);
    t17 = t11./2.0;
    t18 = t11./4.0;
    t23 = t13+t18+t22;
    t25 = t17+t19+t22;
    t24 = dq1.*t23;
    t26 = dq1.*t25;
    C = reshape([-dq3.*t23-dq2.*t25,t26,t24,-t26,t16,t14,-t24,-t14+t16,0.0],[3,3]);
end
if nargout > 2
    G = [0.0;t2.*(9.81e+2./2.0e+1)+t20;t20];
end
