function Jee = get_Jee(q1,q2,q3)
%get_Jee
%    Jee = get_Jee(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Aug-2023 17:48:20

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q2+q3;
t7 = t3.*5.0;
t8 = t5.*5.0;
t9 = cos(t6);
t10 = sin(t6);
t11 = t9.*4.0;
t12 = t10.*4.0;
t13 = t9.*(2.0./5.0);
t14 = t7+t11;
t15 = t8+t12;
Jee = reshape([t4.*t14.*(-1.0./1.0e+1),(t2.*t14)./1.0e+1,0.0,t2.*t15.*(-1.0./1.0e+1),t4.*t15.*(-1.0./1.0e+1),t3./2.0+t13,t2.*t10.*(-2.0./5.0),t4.*t10.*(-2.0./5.0),t13],[3,3]);
end
