function dJee = get_dJee(q1,q2,q3,dq1,dq2,dq3)
%get_dJee
%    dJee = get_dJee(Q1,Q2,Q3,DQ1,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Aug-2023 18:43:49

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q2+q3;
t7 = t3.*5.0;
t8 = t5.*5.0;
t9 = cos(t6);
t10 = sin(t6);
t11 = t9.*4.0;
t12 = t10.*4.0;
t13 = dq3.*t2.*t9.*(2.0./5.0);
t14 = dq3.*t4.*t9.*(2.0./5.0);
t15 = t7+t11;
t16 = t8+t12;
t17 = -t13;
t18 = -t14;
dJee = reshape([dq3.*t4.*t10.*(2.0./5.0)-(dq1.*t2.*t15)./1.0e+1+(dq2.*t4.*t16)./1.0e+1,dq3.*t2.*t10.*(-2.0./5.0)-(dq1.*t4.*t15)./1.0e+1-(dq2.*t2.*t16)./1.0e+1,0.0,t17-(dq2.*t2.*t15)./1.0e+1+(dq1.*t4.*t16)./1.0e+1,t18-(dq1.*t2.*t16)./1.0e+1-(dq2.*t4.*t15)./1.0e+1,dq3.*t10.*(-2.0./5.0)-dq2.*(t5./2.0+t10.*(2.0./5.0)),t17-dq2.*t2.*t9.*(2.0./5.0)+dq1.*t4.*t10.*(2.0./5.0),t18-dq1.*t2.*t10.*(2.0./5.0)-dq2.*t4.*t9.*(2.0./5.0),t10.*(dq2+dq3).*(-2.0./5.0)],[3,3]);
