function M = get_inertia_matrix(q2,q3)
%GET_INERTIA_MATRIX
%    M = GET_INERTIA_MATRIX(Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Aug-2023 16:50:13

t2 = cos(q3);
t3 = q2.*2.0;
t4 = t2./2.0;
t5 = t4+6.7e+1./2.4e+2;
M = reshape([t4+cos(q3.*2.0+t3).*(6.1e+1./4.8e+2)+cos(q3+t3)./2.0+cos(t3).*(2.47e+2./2.4e+2)+4.9e+1./3.2e+1,0.0,0.0,0.0,t2+1.91e+2./8.0e+1,t5,0.0,t5,6.7e+1./2.4e+2],[3,3]);
